name: build-push-ghcr
on:
  workflow_call:
    inputs:
      image:
        required: false
        type: string
        default: ""
      context:
        required: false
        type: string
        default: "."

jobs:
  build:
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    name: build-${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 15
    steps:
      - name: validate input
        run: |
          regex='^([A-Za-z.\/\-]+)?$'
          if [[ "${{ inputs.image }}" =~ $regex ]]; then
            echo "Valid docker image name"
          else
            echo "Invalid docker image name"
            exit 1
          fi
          if [[ "${{ inputs.context }}" =~ $regex ]]; then
            echo "Valid docker context"
          else
            echo "Invalid docker context"
            exit 1
          fi

      - name: ghcr Login
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: lehigh-university-libraries/gha
          path: gha
          sparse-checkout: |
            ci/gha-extract-docker-vars.sh
          sparse-checkout-cone-mode: false
      - run: ./gha/ci/gha-extract-docker-vars.sh
        id: vars
        env:
          DOCKER_IMAGE: ghcr.io/lehigh-university-libraries/${{ inputs.image }}

      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: build+push GHCR
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6
        with:
          context: ${{ inputs.context }}
          push: true
          cache-from: ${{ steps.vars.outputs.cache-from }}
          cache-to: ${{ steps.vars.outputs.cache-to }}
          tags: |
            ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}-${{ steps.vars.outputs.platform }}
  merge:
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      - name: ghcr Login
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          repository: lehigh-university-libraries/gha
          path: gha
          sparse-checkout: |
            ci/gha-extract-docker-vars.sh
          sparse-checkout-cone-mode: false
      - run: ./gha/ci/gha-extract-docker-vars.sh
        id: vars
        env:
          DOCKER_IMAGE: ghcr.io/lehigh-university-libraries/${{ inputs.image }}

      - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

      - name: merge platform images
        run: |
          docker buildx imagetools create \
            -t "${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}" \
            "${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}-amd64" \
            "${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.tag }}-arm64"
