name: bump and release
on:
  workflow_call:
    inputs:
      workflow_file:
        description: 'Optional workflow file to run with gh workflow'
        required: false
        type: string
jobs:
  bump-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # v4
        with:
          fetch-depth: 0

      - name: install autotag binary
        run: |
          gh release download "$TAG" --repo "$REPO" --pattern "$BINARY"
          chmod +x "$BINARY"
          sudo mv "$BINARY" /usr/bin/autotag
        env:
          REPO: autotag-dev/autotag
          BINARY: autotag_linux_amd64
          TAG: v1.4.1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump git tag and create GitHub Release
        run: |-
          TAG=$(autotag)
          git tag "$TAG"
          git push origin "$TAG"
          gh release create "$TAG" --title "$TAG" --generate-notes
          if [ "${{ inputs.workflow_file }}" != "" ]; then
            gh workflow run ${{ inputs.workflow_file }} --ref $TAG
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
