name: shellcheck
on:
  push:
    branches:
      - "**"
jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - run: shellcheck ci/*.sh
